# https://github.com/awesome-containers/static-tar
ARG STATIC_TAR_VERSION=1.34
ARG STATIC_TAR_IMAGE=ghcr.io/awesome-containers/static-tar

# https://github.com/awesome-containers/static-gzip
ARG STATIC_GZIP_VERSION=5.2.1
ARG STATIC_GZIP_IMAGE=ghcr.io/awesome-containers/static-gzip

# https://github.com/awesome-containers/alpine-build-essential
ARG BUILD_ESSENTIAL_VERSION=3.17
ARG BUILD_ESSENTIAL_IMAGE=ghcr.io/awesome-containers/alpine-build-essential


FROM $STATIC_TAR_IMAGE:$STATIC_TAR_VERSION-slim AS static-tar
FROM $STATIC_GZIP_IMAGE:$STATIC_GZIP_VERSION AS static-gzip
FROM $BUILD_ESSENTIAL_IMAGE:$BUILD_ESSENTIAL_VERSION AS build

WORKDIR /src/gzip
COPY --from=static-gzip /bin/ ./

RUN set -xeu; \
    rm -rf bash tar;\
    upx --no-progress --no-color gzip; \
    upx -t --no-progress --no-color gzip; \
    chmod -cR 755 gzip; \
    chown -cR 0:0 gzip; \
    ! ldd gzip && :; \
    ./gzip --version

# slim static tar image
FROM static-tar
COPY --from=build /src/gzip/ /bin/
